name: Full update
on: 
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'
jobs:
  full-update:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.6.15' 
      - name: Build
        env:
          GITHUB_TOKEN: ${{ secrets.USER_GITHUB_TOKEN }}
          SRC_ORG: ${{ secrets.SRC_ORG }}
          DST_ORG: ${{ secrets.DST_ORG }}
        run: |
            pip install pygithub
            python -u mirror_github_org.py --full-run
